dist: trusty
sudo: false
language: java
services:
  - docker
before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - ./gradlew clean build -DbuildNumber="$TRAVIS_BUILD_NUMBER"
  - ./gradlew dockerPush -DbuildNumber="$TRAVIS_BUILD_NUMBER"
  - ./gradlew dockerPushlatest -DbuildNumber="$TRAVIS_BUILD_NUMBER"
